[package]
name = "nvptx_crate_example"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

[dependencies]
accel-core = "*"
nvptx-panic = { path = "../nvptx-panic" }

[package.metadata.nvptx]
runtime = ["core"]
